// 台パネル用フォント（候補比較中。決定後に不要なものを外す）
import '@fontsource/shippori-mincho/600.css';
import '@fontsource/shippori-mincho/800.css';
import '@fontsource/cinzel/600.css';
import '@fontsource/playfair-display/600.css';
import '@fontsource/zen-old-mincho/600.css';
import '@fontsource/zen-old-mincho/900.css';
import '@fontsource/cormorant-garamond/600.css';
import '@fontsource/zen-kaku-gothic-new/500.css';
import '@fontsource/zen-kaku-gothic-new/700.css';
import '@fontsource/montserrat/300.css';
import '@fontsource/montserrat/500.css';
